server:
  port: 8888

encrypt:
  key: testconfigencryptorkeytestconfigencryptorkeytestconfigencryptorkey

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/K-Diger/SpringCloud-Config
          default-label: main
