server:
  port: 8000

jwt:
  secret-key: smilegatedigermsaauthserversmilegatedigermsaauthserversmilegatedigermsaauthserver

spring:
  cloud:
    config:
      name: api-gateway
      profile: dev
    gateway:
      default-filters:
        - name: AuthenticationFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/?(?<segment>.*), /$\{segment}

        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/post-service/**
          filters:
            - RewritePath=/post-service/?(?<segment>.*), /$\{segment}
            - AuthenticationFilter

  application:
    name: api-gateway

  main:
    web-application-type: reactive

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh