server:
  port: 8000

spring:
  application:
    name: api-gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smilegatedevcamp?Unicode=true&characterEncoding=utf8
    username: root
    password: 112233
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: http://localhost:8081/
#          predicates:
#            - Path=/v1/user/**
#        - id: user-service
#          uri: http://localhost:8083/
#          predicates:
#            - Path=/v1/user/**
#
#        - id: post-service
#          uri: http://localhost:8082/
#          predicates:
#            - Path=/v1/post/**

jwt:
  secret-key: smilegatedigermsaauthserversmilegatedigermsaauthserversmilegatedigermsaauthserver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka