server:
  port: 8000

spring:
  application:
    name: apigateway

jwt:
  secret-key: smilegatedigermsaauthserversmilegatedigermsaauthserversmilegatedigermsaauthserver

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka